<main class="container  text-center">
        <header class="row border-0 mt-5">
            <div class="col mt-5">
                    <h1 class="titulo">Video Tape</h1>
            </div>
        </header>
            
        <section class="row">
            <div class="col-md-5">
                <img class="w-100 p-hidden" src="img/Resting _Monochromatic.png" alt="filme">
            </div>

			<div class="col-md-7 align-self-center">
                <p class="textS">Buy your favorite movie at video tape.</p>

             	<a class="btn botao" href="/login">Login</a>

                <a class="btn botao mt-3" href="/sign_up">Sign up</a>
            </div>
        </section>


</main>