<main class="container mt-5 text-center">
        <header class="row mt-5 border-0">
            <div class="col mt-5">
                <h1 class="titulo">Sign up</h1>
            </div>
        </header>

       <section class="row">
            <div class="col-md-5">
                <img class="w-100 p-hidden" src="img/Authentication_Isometric.png" alt="foto de autenticação">
            </div>

            <div class="col-md-7 align-self-center">
                <form action="/register" method="post">
                    <input type="text" class="entrada w-50" name="nome_register" placeholder="Digite seu nome completo">

                    <input type="email" class="entrada mt-3 w-50" name="email_register" placeholder="Digite seu email">

                    <input type="password" class="entrada mt-3 w-50" name="senha_register" placeholder="Digite sua senha">

                    <input type="text" class="entrada mb-3 mt-3 w-50" name="cpf_register" placeholder="Digite seu cpf" pattern="[0-9]{3}.[0-9]{3}.[0-9]{3}-[0-9]{2}">

                    <small>Selecione a data de nascimento</small>
                    <input class="entrada w-50 text-center" type="date" name="date_register"><br>
                    <?php if($this->view->erroCadastro) { ?>
                        <div class="col">
                            <p class="textS">Por favor,verifique se os campos estão preenchidos corretamente</p>
                        </div>
                    <?php } ?>

                    <?php if($this->view->dadosCadastrados) { ?>
                        <div class="col">
                            <p class="textS">Seus dados já está sendo usados em outra conta, por favor acesse sua conta</p>
                        </div>
                    <?php } ?>
                    <button class="btn botao mt-4" type="submit">Login</button>
                </form>
            </div>
       </section>
        
    </main>   