<main class="container">
        <section class="row">
            <div class="col">
                <h3 class="titulo">Sobre Nós</h3>
            </div>
        </section>

        <section class="row mt-5 ">
                <div class="col-md-8">

                    <h5 class="titulo">Nossa história</h5>

                    <p class="textS text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in ornare sapien. Sed venenatis gravida nunc, eu sollicitudin turpis consectetur ut. In vel suscipit ante. Fusce luctus tempus nibh id ultricies. Mauris eleifend, diam eu tempor tristique, felis odio vehicula quam, ut pretium lacus dui ac ante. Mauris euismod sapien sit amet ornare condimentum. Proin ut ligula orci.</p>
                </div>

                <div class="col-md-4">
                    <h5 class="titulo">Contato</h5>
                    <p class="textS">Telefone: (48) 3233-9800</p>
                    <p class="textS">Email: teste@teste.com</p>
                    <p class="textS">whatsapp:(48)9 2000-0000</p>
                </div>
        </section>

        <section class="row mt-3">
            <div class="col text-center">
                <h4 class="titulo mb-3">Nossa Localização</h4>

                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14027.475724673977!2d-49.01837626806646!3d-28.483493619627467!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x952142e54d47d5c7%3A0x2e6b8f2ec2d454bd!2sCentro%2C%20Tubar%C3%A3o%20-%20SC!5e0!3m2!1spt-BR!2sbr!4v1626806115418!5m2!1spt-BR!2sbr" width="800" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>
        </section>

    </main>