<main class="container">
        <section class="row">
            <div class="col">
                <h3 class="titulo"> <?= $this->view->infoMovie['nome']?></h3>
            </div>
        </section>

        <section class="row mt-3 ">
            <div class="col-md-3 text-center">
                <img class="img-home" src="<?= $this->view->infoMovie['poster']?>" alt="poster">
            </div>

            <div class="col-md-8 ml-5">
                <p class="textS text-justify"><?= $this->view->infoMovie['sinopse']?></p>

                <p>Data de lançamento: <?= $this->view->infoMovie['dataLancamento'] ?></p>
                <p>Diretor(a): <?= $this->view->infoMovie['diretor']?></p>
                <p>Gênero(s): <?= $this->view->infoMovie['genero']?></p>
                <?php if(!$_SESSION['funcionario']) { ?>
                    <a onclick="thanks(<?= $this->view->infoMovie['id'] ?>,<?=$_SESSION['id'] ?>)" class="btn botao-nav" href="<?= $this->view->infoMovie['video'] ?>" download="<?=  $this->view->infoMovie['download'] ?>" type="video/mp4">Baixar</a>
                <?php } ?>

                <?php if($_SESSION['funcionario']) { ?>
                    <a class="btn botao-nav" href="/edit_movie?id=<?= $this->view->infoMovie['id'] ?>">Editar</a>
                <?php } ?>
            </div>
        </section>
    </main>

<script>

    function thanks(idFilme , idCliente){
        window.location.replace('/thanks?filme='+idFilme+'&cliente='+idCliente)
    }

</script>