<main class="container">
    <section class="row">
        <div class="col">
            <h3 class="titulo"><?= $_GET['search'] ?></h3>
        </div>
    </section>

    <section class="row mt-3">
    <?php foreach($this->view->infoPage as $info) { ?>
            <div class="col-md-4  mt-2">
                <div class="text-center">
                    <img class="img-home pt-2" src="<?= $info['poster'] ?>" alt="poster">
                    <a class="textS link-home" href="/movie?id=<?= $info['id'] ?>"> <?= $info['nome'] ?> </a>
                </div>  
            </div>
    <?php } ?>
    </section>
</main>