<main class="container">
        <section class="row">
            <div class="col">
                <h3 class="titulo">Registro de Funcionários</h3>
            </div>
        </section>

        <section class="row ">
               <div class="col-md-5 ">
                    <img class="w-100 p-hidden" src="img/Avatar_Isometric.png" alt="foto geneerica de avatares">
               </div>

               <div class="col-md-7 align-self-center  text-center">
                    <form action="/insert_func" method="post">
                        <input class="entrada" type="text" placeholder="nome completo" name="nome_func">

                        <input class="entrada" type="email" placeholder="email" name="email_func">

                        <input class="entrada" type="password" placeholder="senha" name="senha_func">

                        <input class="entrada" type="text" placeholder="CPF" name="cpf_func" pattern="[0-9]{3}.[0-9]{3}.[0-9]{3}-[0-9]{2}">

                        <input class="entrada" type="text" placeholder="RG" name="rg_func" pattern="[0-9]{1}.[0-9]{3}.[0-9]{3}">

                        <input class="entrada mb-2" type="text" placeholder="telefone" pattern="[0-9]{2} 9[0-9]{4}-[0-9]{4}" name="telefone_func">
                        
                        <small>Selecione a data de nascimento</small>
                        <input id="lanc_filme" type="date" name="diaNascimento_func" class="entrada w-50"><br>

                        <button class="btn botao mt-3" type="submit">Registrar</button>
                    </form>

                    <?php if(isset($_GET['insert']) && $_GET['insert'] == 1) { ?>
                        <p class="textS mt-3">Registro feito com sucesso!</p>
                    <?php } ?>

                    <?php if(isset($_GET['insert']) && $_GET['insert'] == 2) { ?>
                        <p class="textS mt-3">Por favor, verifique se os campos estão preenchidos corretamente</p>
                    <?php } ?>
               </div>
        </section>
    </main>