<main class="container">
        <article class="row">
            <section class="col mt-3">
                <h3 class="titulo">Thanks</h3>
            </section>
        </article>

        <article class="row">
            <section class="col-md-5 align-self-center">
                <img class="w-100 h-50 p-hidden" src="img/Happy face_Monochromatic.png" alt="picture of happy face">
            </section>

            <section class="col-md-7 align-self-center text-center">
                <p class="textS">Thanks for download our movie and enjoy the movie!!!</p>
                <p class="textS">Click for go home</p>
                <a class="btn botao" href="/home">Home</a>
            </section>
        </article>
</main>
