<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Video Tape</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

        <link rel="stylesheet" href="css/style.css">
    </head>
    <body>

    <header>
        <div class="container">
            <div class="row">
                <div class="col">
                    <nav class="navbar navbar-expand-md">

                        <a href="/home" class="navbar-brand titulo">Video Tape</a>

                        <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-target">
                            <i class="fas fa-bars"></i>
                        </button>

                        <div class="collapse navbar-collapse " id="nav-target">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <a href="/home" class="nav-link">Home</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="/perfil">Perfil</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="/about">Sobre nós</a>
                                </li>

                                <?php if(isset( $_SESSION['funcionario']) &&  $_SESSION['funcionario'] == true) {  ?>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" data-toggle="dropdown">Registrar</a>
  
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" href="/register_movie">Registrar Filme</a>
                                            <a class="dropdown-item" href="/register_func">Registrar Funcionário</a>
                                        </div>
                                    </li>
                                <?php } ?>


                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown">Gêneros</a>

                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="/page?search=Animação">Animação</a>
                                        <a class="dropdown-item" href="/page?search=Ação">Ação</a>
                                        <a class="dropdown-item" href="/page?search=Comédia ">Comédia</a>
                                        <a class="dropdown-item" href="/page?search=Drama">Drama</a>
                                        <a class="dropdown-item" href="/page?search=Documentário">Documentário</a>
                                        <a class="dropdown-item" href="/page?search=Ficção Científica">Ficção Científica</a>
                                        <a class="dropdown-item" href="/page?search=Suspense">Suspense</a>
                                        <a class="dropdown-item" href="/page?search=Terror">Terror</a>
                                    </div>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="/out">Sair</a>
                                </li>

                                <form action="/search_movie" method="GET" class="form-inline">
                                    <input class="entrada w-lg-50" type="text" name="search" placeholder="Pesquise o filme aqui">
                                    <button class="botao-nav ml-2" type="submit">Pesquisar</button>
                                </form>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <?= $this->content() ?>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>     	
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
</body>